// AUTO-GENERATED by tauri-specta from src-tauri/src/lib.rs. Do not edit; run `bun run tauri dev` to refresh.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	getDiagnostics: () => __TAURI_INVOKE<SystemDiagnostics>("get_diagnostics"),
	getConfig: () => __TAURI_INVOKE<AppConfig>("get_config").then((v) => (({...v,trail:({...v.trail,layers:v.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...v.head,color:v.head.color.map(i=>i)}),ripple:({...v.ripple,color_left:v.ripple.color_left.map(i=>i),color_right:v.ripple.color_right.map(i=>i),color_middle:v.ripple.color_middle.map(i=>i)}),particles:({...v.particles,color:v.particles.color.map(i=>i)}),satellites:({...v.satellites,color:v.satellites.color.map(i=>i)})}) as typeof v)),
	updateConfig: (newConfig: AppConfig) => __TAURI_INVOKE<null>("update_config", { newConfig: ({...newConfig,trail:({...newConfig.trail,layers:newConfig.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...newConfig.head,color:newConfig.head.color.map(i=>i)}),ripple:({...newConfig.ripple,color_left:newConfig.ripple.color_left.map(i=>i),color_right:newConfig.ripple.color_right.map(i=>i),color_middle:newConfig.ripple.color_middle.map(i=>i)}),particles:({...newConfig.particles,color:newConfig.particles.color.map(i=>i)}),satellites:({...newConfig.satellites,color:newConfig.satellites.color.map(i=>i)})}) }),
	toggleOverlay: () => __TAURI_INVOKE<boolean>("toggle_overlay"),
	resetDefaults: () => __TAURI_INVOKE<AppConfig>("reset_defaults").then((v) => (({...v,trail:({...v.trail,layers:v.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...v.head,color:v.head.color.map(i=>i)}),ripple:({...v.ripple,color_left:v.ripple.color_left.map(i=>i),color_right:v.ripple.color_right.map(i=>i),color_middle:v.ripple.color_middle.map(i=>i)}),particles:({...v.particles,color:v.particles.color.map(i=>i)}),satellites:({...v.satellites,color:v.satellites.color.map(i=>i)})}) as typeof v)),
	/**  Writes the current configuration to disk immediately (bypassing the autosave debounce). */
	saveConfig: () => __TAURI_INVOKE<string>("save_config"),
	/**  Built-in presets, with Rust as the single source of truth. */
	listPresets: () => __TAURI_INVOKE<PresetInfo[]>("list_presets").then((v) => (v.map(i=>({...i,config:({...i.config,trail:({...i.config.trail,layers:i.config.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...i.config.head,color:i.config.head.color.map(i=>i)}),ripple:({...i.config.ripple,color_left:i.config.ripple.color_left.map(i=>i),color_right:i.config.ripple.color_right.map(i=>i),color_middle:i.config.ripple.color_middle.map(i=>i)}),particles:({...i.config.particles,color:i.config.particles.color.map(i=>i)}),satellites:({...i.config.satellites,color:i.config.satellites.color.map(i=>i)})})})) as typeof v)),
	applyPreset: (id: string) => __TAURI_INVOKE<AppConfig>("apply_preset", { id }).then((v) => (({...v,trail:({...v.trail,layers:v.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...v.head,color:v.head.color.map(i=>i)}),ripple:({...v.ripple,color_left:v.ripple.color_left.map(i=>i),color_right:v.ripple.color_right.map(i=>i),color_middle:v.ripple.color_middle.map(i=>i)}),particles:({...v.particles,color:v.particles.color.map(i=>i)}),satellites:({...v.satellites,color:v.satellites.color.map(i=>i)})}) as typeof v)),
	/**
	 *  Imports a user-supplied JSON document through the self-healing deserializer, so partial or
	 *  slightly broken files still apply cleanly. Returns the healed config and what was repaired.
	 */
	importConfig: (json: string) => __TAURI_INVOKE<ImportOutcome>("import_config", { json }).then((v) => (({...v,config:({...v.config,trail:({...v.config.trail,layers:v.config.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...v.config.head,color:v.config.head.color.map(i=>i)}),ripple:({...v.config.ripple,color_left:v.config.ripple.color_left.map(i=>i),color_right:v.config.ripple.color_right.map(i=>i),color_middle:v.config.ripple.color_middle.map(i=>i)}),particles:({...v.config.particles,color:v.config.particles.color.map(i=>i)}),satellites:({...v.config.satellites,color:v.config.satellites.color.map(i=>i)})})}) as typeof v)),
	/**  Backend log history for the Dev Console (newer records arrive via the `rust-log` event). */
	getRecentLogs: () => __TAURI_INVOKE<LogRecord[]>("get_recent_logs").then((v) => (v.map(i=>i) as typeof v)),
	/**
	 *  Renders the current overlay frame to a PNG (composited over dark grey) and returns its path.
	 *  `width` / `height` = crop size centred on the cursor; 0 = whole overlay.
	 */
	captureOverlay: (width: number, height: number) => __TAURI_INVOKE<string>("capture_overlay", { width, height }),
	/**
	 *  Stores the live configuration as a named user preset (`<config dir>/presets/user-<slug>.json`)
	 *  and selects it. Saving under an existing name overwrites that preset.
	 */
	saveUserPreset: (name: string, description: string) => __TAURI_INVOKE<PresetInfo>("save_user_preset", { name, description }).then((v) => (({...v,config:({...v.config,trail:({...v.config.trail,layers:v.config.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...v.config.head,color:v.config.head.color.map(i=>i)}),ripple:({...v.config.ripple,color_left:v.config.ripple.color_left.map(i=>i),color_right:v.config.ripple.color_right.map(i=>i),color_middle:v.config.ripple.color_middle.map(i=>i)}),particles:({...v.config.particles,color:v.config.particles.color.map(i=>i)}),satellites:({...v.config.satellites,color:v.config.satellites.color.map(i=>i)})})}) as typeof v)),
	/**  Deletes a user preset and returns the refreshed preset list. Built-ins are refused. */
	deleteUserPreset: (id: string) => __TAURI_INVOKE<PresetInfo[]>("delete_user_preset", { id }).then((v) => (v.map(i=>({...i,config:({...i.config,trail:({...i.config.trail,layers:i.config.trail.layers.map(i=>({...i,start_color:i.start_color.map(i=>i),end_color:i.end_color.map(i=>i)}))}),head:({...i.config.head,color:i.config.head.color.map(i=>i)}),ripple:({...i.config.ripple,color_left:i.config.ripple.color_left.map(i=>i),color_right:i.config.ripple.color_right.map(i=>i),color_middle:i.config.ripple.color_middle.map(i=>i)}),particles:({...i.config.particles,color:i.config.particles.color.map(i=>i)}),satellites:({...i.config.satellites,color:i.config.satellites.color.map(i=>i)})})})) as typeof v)),
};

/* Types */
export type AppConfig = {
	enabled: boolean,
	effect_mode: EffectMode,
	general: GeneralConfig,
	trail: TrailConfig,
	head: HeadConfig,
	ripple: RippleConfig,
	particles: ParticleConfig,
	satellites: SatelliteConfig,
	rainbow: RainbowConfig,
	fps_counter: FpsCounterConfig,
};

export type EffectMode = "FourLayerGlow" | "Ribbon" | "ParticlesOnly" | "SatellitesOnly" | "Minimal";

export type FpsCounterConfig = {
	enabled: boolean,
	refresh_rate_ms: number,
	align_right: boolean,
	align_bottom: boolean,
};

/**  Rolling render-loop statistics, refreshed by the render thread roughly twice a second. */
export type FrameStats = {
	/**  Presented frames per second over the last window (0 while idle). */
	fps: number,
	/**  Average CPU time per presented frame in milliseconds (physics + mesh + submit). */
	frame_ms: number,
	/**  "active" (animating), "settling" (flushing final frames) or "idle" (parked). */
	state: string,
	/**  Ribbon vertices uploaded in the last frame. */
	ribbon_vertices: number,
	/**  SDF instances (head, ripples, particles, satellites) in the last frame. */
	instances: number,
};

export type GeneralConfig = {
	autostart: boolean,
	minimize_to_tray: boolean,
	start_minimized: boolean,
	global_hotkey: string,
	selected_preset: string,
	/**  Frame-rate cap for the overlay render loop. `0` = match the display refresh rate. */
	max_fps?: number,
};

export type GpuInfo = {
	adapter: string,
	backend: string,
	device_type: string,
};

export type HeadConfig = {
	enabled: boolean,
	size: number,
	squish_intensity: number,
	squish_smoothing: number,
	color: [number, number, number, number],
	filled: boolean,
	thickness: number,
};

export type ImportOutcome = {
	config: AppConfig,
	repaired_paths: string[],
};

export type LayerConfig = {
	enabled: boolean,
	start_color: [number, number, number, number],
	end_color: [number, number, number, number],
	width_factor: number,
	alpha_factor: number,
	start_blur: number,
	end_blur: number,
};

export type LogRecord = {
	level: string,
	target: string,
	message: string,
	/**  Milliseconds since the Unix epoch. */
	timestamp_ms: number,
};

export type ParticleConfig = {
	enabled: boolean,
	count_per_click: number,
	duration_ms: number,
	base_speed: number,
	gravity: number,
	friction: number,
	size: number,
	color: [number, number, number, number],
};

export type PresetInfo = {
	id: string,
	name: string,
	description: string,
	config: AppConfig,
};

export type RainbowConfig = {
	enabled: boolean,
	speed: number,
	saturation: number,
	lightness: number,
};

export type RippleConfig = {
	enabled: boolean,
	max_diameter: number,
	duration_ms: number,
	start_width: number,
	color_left: [number, number, number, number],
	color_right: [number, number, number, number],
	color_middle: [number, number, number, number],
};

export type SatelliteConfig = {
	enabled: boolean,
	count: number,
	orbit_diameter: number,
	size: number,
	speed: number,
	dual_ring: boolean,
	show_orbit_ring: boolean,
	orbit_ring_thickness: number,
	color: [number, number, number, number],
};

export type SystemDiagnostics = {
	os: string,
	arch: string,
	portable: boolean,
	app_version: string,
	config_path: string,
	screen_virtual_origin: [number, number],
	screen_virtual_size: [number, number],
	gpu: GpuInfo | null,
	/**  "hook" when the OS-level mouse hook is delivering events, otherwise "poll". */
	input_backend: string,
	uptime_secs: number,
	debug_build: boolean,
	frame: FrameStats,
	/**
	 *  Result of the last global-hotkey registration, e.g. "registered 'Ctrl+Shift+E'" or an
	 *  error message when another application owns the shortcut.
	 */
	hotkey_status: string,
	/**  Display refresh rate the render loop paces to when `general.max_fps` is 0. */
	display_refresh_hz: number,
};

export type TrailConfig = {
	enabled: boolean,
	length: number,
	spring: number,
	damping: number,
	head_spring: number,
	head_damping: number,
	/**
	 *  Number of leading nodes (including the head) that follow without overshoot; the rest of
	 *  the chain is spring-driven and may whip. Keeps the ribbon clean right at the pointer.
	 */
	lead_nodes?: number,
	cursor_size: number,
	min_width: number,
	velocity_width_mult: number,
	velocity_alpha_mult: number,
	interpolation_steps: number,
	fade_mode: number,
	enable_gradient: boolean,
	adaptive_quality: boolean,
	layers: [LayerConfig, LayerConfig, LayerConfig, LayerConfig],
};

