// AUTO-GENERATED by tauri-specta from src-tauri/src/lib.rs. Do not edit; run `bun run tauri dev` to refresh.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	getDiagnostics: () => __TAURI_INVOKE<SystemDiagnostics_Serialize>("get_diagnostics"),
	getConfig: () => __TAURI_INVOKE<AppConfig_Serialize>("get_config"),
	updateConfig: (newConfig: AppConfig_Deserialize) => __TAURI_INVOKE<null>("update_config", { newConfig }),
	toggleOverlay: () => __TAURI_INVOKE<boolean>("toggle_overlay"),
	resetDefaults: () => __TAURI_INVOKE<AppConfig_Serialize>("reset_defaults"),
	/**  Writes the current configuration to disk immediately (bypassing the autosave debounce). */
	saveConfig: () => __TAURI_INVOKE<string>("save_config"),
	listPresets: () => __TAURI_INVOKE<PresetInfo_Serialize[]>("list_presets"),
	applyPreset: (id: string) => __TAURI_INVOKE<AppConfig_Serialize>("apply_preset", { id }),
	/**
	 *  Imports a user-supplied JSON document through the self-healing deserializer, so partial or
	 *  slightly broken files still apply cleanly. Returns the healed config and what was repaired.
	 */
	importConfig: (json: string) => __TAURI_INVOKE<ImportOutcome_Serialize>("import_config", { json }),
	/**  Backend log history for the Dev Console (newer records arrive via the `rust-log` event). */
	getRecentLogs: () => __TAURI_INVOKE<LogRecord[]>("get_recent_logs"),
	/**
	 *  Renders the current overlay frame to a PNG (composited over dark grey) and returns its path.
	 *  `width` / `height` = crop size centred on the cursor; 0 = whole overlay.
	 */
	captureOverlay: (width: number, height: number) => __TAURI_INVOKE<string>("capture_overlay", { width, height }),
	/**
	 *  Stores the live configuration as a named user preset (`<config dir>/presets/user-<slug>.json`)
	 *  and selects it. Saving under an existing name overwrites that preset.
	 */
	saveUserPreset: (name: string, description: string) => __TAURI_INVOKE<PresetInfo_Serialize>("save_user_preset", { name, description }),
	/**  Deletes a user preset and returns the refreshed preset list. Built-ins are refused. */
	deleteUserPreset: (id: string) => __TAURI_INVOKE<PresetInfo_Serialize[]>("delete_user_preset", { id }),
};

/* Types */
/**  Root configuration tree for FXCursor, persisted to `config.json`. */
export type AppConfig = AppConfig_Serialize | AppConfig_Deserialize;

/**  Root configuration tree for FXCursor, persisted to `config.json`. */
export type AppConfig_Deserialize = {
	/**
	 *  Version of the parameter units this file was written with. Read by
	 *  [`crate::migrate`] to convert older documents; do not edit by hand.
	 */
	schema_version?: number,
	/**  Master toggle for all overlay cursor effects. */
	enabled: boolean,
	/**  Active effect mode gating visual components. */
	effect_mode: EffectMode,
	/**  General application and OS integration settings. */
	general: GeneralConfig_Deserialize,
	/**  Ribbon trail physics and 4-layer master design parameters. */
	trail: TrailConfig_Deserialize,
	/**  Velocity-elongated SDF cursor head settings. */
	head: HeadConfig,
	/**  Click-triggered expanding shockwave ripple settings. */
	ripple: RippleConfig,
	/**  Click-triggered particle burst settings. */
	particles: ParticleConfig,
	/**  Orbiting satellite bodies settings. */
	satellites: SatelliteConfig,
	/**  Rainbow chromatic hue cycling settings. */
	rainbow: RainbowConfig,
	/**  On-overlay FPS HUD counter settings. */
	fps_counter: FpsCounterConfig,
	/**  GPU-rendered system-cursor bypass settings (missing in older config files). */
	gpu_cursor?: GpuCursorConfig,
};

/**  Root configuration tree for FXCursor, persisted to `config.json`. */
export type AppConfig_Serialize = {
	/**
	 *  Version of the parameter units this file was written with. Read by
	 *  [`crate::migrate`] to convert older documents; do not edit by hand.
	 */
	schema_version: number,
	/**  Master toggle for all overlay cursor effects. */
	enabled: boolean,
	/**  Active effect mode gating visual components. */
	effect_mode: EffectMode,
	/**  General application and OS integration settings. */
	general: GeneralConfig_Serialize,
	/**  Ribbon trail physics and 4-layer master design parameters. */
	trail: TrailConfig_Serialize,
	/**  Velocity-elongated SDF cursor head settings. */
	head: HeadConfig,
	/**  Click-triggered expanding shockwave ripple settings. */
	ripple: RippleConfig,
	/**  Click-triggered particle burst settings. */
	particles: ParticleConfig,
	/**  Orbiting satellite bodies settings. */
	satellites: SatelliteConfig,
	/**  Rainbow chromatic hue cycling settings. */
	rainbow: RainbowConfig,
	/**  On-overlay FPS HUD counter settings. */
	fps_counter: FpsCounterConfig,
	/**  GPU-rendered system-cursor bypass settings (missing in older config files). */
	gpu_cursor: GpuCursorConfig,
};

/**  Global rendering preset/mode selector controlling which visual subsystems are active. */
export type EffectMode = 
/**
 *  Everything may draw: 4-layer ribbon, head, ripples, particles and satellites (each still
 *  gated by its own `enabled` flag).
 */
"FourLayerGlow" | 
/**  Ribbon trail and cursor head only; disables click ripples, particles, and satellites. */
"Ribbon" | 
/**  Click feedback only: cursor head, shockwave ripples, and particle bursts. */
"ParticlesOnly" | 
/**  Orbitals only: cursor head and orbiting satellites. */
"SatellitesOnly" | 
/**  Minimal low-profile: crisp core and inner spine layers only with cursor head. */
"Minimal";

/**  On-overlay FPS heads-up display (HUD) rendered with a 3×5 bitmap font. */
export type FpsCounterConfig = {
	/**  Whether the FPS counter HUD is drawn on the overlay. */
	enabled: boolean,
	/**
	 *  Update interval for the HUD text in milliseconds. Frame statistics are gathered in
	 *  500 ms windows, so values below 500 behave like 500.
	 */
	refresh_rate_ms: number,
	/**  If true, aligns HUD to the right side of the screen; left otherwise. */
	align_right: boolean,
	/**  If true, aligns HUD to the bottom of the screen; top otherwise. */
	align_bottom: boolean,
};

/**  Rolling render-loop statistics, refreshed by the render thread roughly twice a second. */
export type FrameStats = {
	/**  Presented frames per second over the last window (0 while idle). */
	fps: number,
	/**  Average CPU time per presented frame in milliseconds (physics + mesh + submit). */
	frame_ms: number,
	/**  "active" (animating), "settling" (flushing final frames) or "idle" (parked). */
	state: string,
	/**  Ribbon vertices uploaded in the last frame. */
	ribbon_vertices: number,
	/**  SDF instances (head, ripples, particles, satellites) in the last frame. */
	instances: number,
};

/**  General application shell and system integration settings. */
export type GeneralConfig = GeneralConfig_Serialize | GeneralConfig_Deserialize;

/**  General application shell and system integration settings. */
export type GeneralConfig_Deserialize = {
	/**  Whether FXCursor launches automatically at operating system login. */
	autostart: boolean,
	/**  Whether closing the main Studio window minimizes it to the system tray. */
	minimize_to_tray: boolean,
	/**  Whether the Studio window starts hidden in the tray on initial launch. */
	start_minimized: boolean,
	/**  Global keyboard shortcut string to toggle effects on/off (e.g. "Ctrl+Shift+E"). */
	global_hotkey: string,
	/**  ID of the currently active preset (built-in or user preset). */
	selected_preset: string,
	/**  Frame-rate cap for the overlay render loop. `0` = match the display refresh rate. */
	max_fps?: number,
};

/**  General application shell and system integration settings. */
export type GeneralConfig_Serialize = {
	/**  Whether FXCursor launches automatically at operating system login. */
	autostart: boolean,
	/**  Whether closing the main Studio window minimizes it to the system tray. */
	minimize_to_tray: boolean,
	/**  Whether the Studio window starts hidden in the tray on initial launch. */
	start_minimized: boolean,
	/**  Global keyboard shortcut string to toggle effects on/off (e.g. "Ctrl+Shift+E"). */
	global_hotkey: string,
	/**  ID of the currently active preset (built-in or user preset). */
	selected_preset: string,
	/**  Frame-rate cap for the overlay render loop. `0` = match the display refresh rate. */
	max_fps: number,
};

/**
 *  GPU-rendered system-cursor bypass: the active OS cursor shape is extracted, drawn on the
 *  overlay with optional movement rotation and a click bounce, and the real cursor can be hidden.
 */
export type GpuCursorConfig = {
	/**  Master toggle for the GPU-drawn cursor shape. */
	enabled: boolean,
	/**
	 *  Replace the system arrow with an invisible cursor while the bypass is active.
	 *  Restored automatically on disable, exit and panic.
	 */
	hide_system_cursor: boolean,
	/**  Rotate the arrow to point along the direction of pointer movement (smoothed). */
	rotate_with_movement: boolean,
	/**
	 *  Rotation easing time constant in 1/60 s frames (1–30): higher is smoother but lags
	 *  further behind direction changes.
	 */
	rotation_smoothing: number,
	/**  Peak click-bounce scale in percent (100 = no bounce, 150 = 1.5×). */
	click_scale_percent: number,
	/**  Click-bounce animation duration in milliseconds. */
	click_scale_duration_ms: number,
};

export type GpuInfo = {
	adapter: string,
	backend: string,
	device_type: string,
};

/**  Configuration for the velocity-elongated SDF cursor head. */
export type HeadConfig = {
	/**  Whether the head shape is rendered at the cursor pointer. */
	enabled: boolean,
	/**  Resting diameter in physical pixels. */
	size: number,
	/**
	 *  Elongation along the direction of motion (0.0–1.0). Applied as
	 *  `scale = min(v × 8, 200) / 15 × intensity`.
	 */
	squish_intensity: number,
	/**
	 *  Fraction of the remaining gap the head (position, squish and angle) closes per 1/120 s
	 *  (0.0–1.0; 1.0 = locked to the pointer).
	 */
	squish_smoothing: number,
	/**  RGBA color of the cursor head (straight alpha, 0.0–1.0). */
	color: [number, number, number, number],
	/**  If true, renders a solid filled ellipse; if false, renders an outlined ring. */
	filled: boolean,
	/**  Stroke thickness when `filled` is false (negative value for filled). */
	thickness: number,
};

export type ImportOutcome = ImportOutcome_Serialize | ImportOutcome_Deserialize;

export type ImportOutcome_Deserialize = {
	config: AppConfig_Deserialize,
	repaired_paths: string[],
};

export type ImportOutcome_Serialize = {
	config: AppConfig_Serialize,
	repaired_paths: string[],
};

/**  Visual properties for one layer of the 4-layer master ribbon. */
export type LayerConfig = {
	/**  Whether this specific layer is rendered. */
	enabled: boolean,
	/**  RGBA start color at the head of the trail (straight alpha, 0.0–1.0). */
	start_color: [number, number, number, number],
	/**  RGBA end color at the tail of the trail (straight alpha, 0.0–1.0). */
	end_color: [number, number, number, number],
	/**  Width multiplier relative to the base trail width (e.g. 1.50 for Outer Glow, 0.15 for Inner Spine). */
	width_factor: number,
	/**  Opacity multiplier applied to this layer's colors (0.0–1.0). */
	alpha_factor: number,
	/**  Blur/feathering fraction at the head of the trail (0.0 = razor sharp, 0.5 = soft feather). */
	start_blur: number,
	/**  Blur/feathering fraction at the tail of the trail (0.0 = razor sharp, 0.5 = soft feather). */
	end_blur: number,
};

export type LogRecord = {
	level: string,
	target: string,
	message: string,
	/**  Milliseconds since the Unix epoch. */
	timestamp_ms: number,
};

/**  Click-triggered particle burst physics and rendering. */
export type ParticleConfig = {
	/**  Whether particle bursts are emitted on mouse clicks. */
	enabled: boolean,
	/**  Number of particles spawned per click event. */
	count_per_click: number,
	/**  Lifetime duration of each particle in milliseconds. */
	duration_ms: number,
	/**  Initial ejection speed in pixels per second. */
	base_speed: number,
	/**  Downward gravity acceleration in pixels per second squared. */
	gravity: number,
	/**  Velocity kept per 1/60 s (0.0–1.0; frame-rate independent via `friction^(dt×60)`). */
	friction: number,
	/**  Particle diameter in physical pixels. */
	size: number,
	/**  RGBA tint color for particles. */
	color: [number, number, number, number],
};

export type PresetInfo = PresetInfo_Serialize | PresetInfo_Deserialize;

export type PresetInfo_Deserialize = {
	id: string,
	name: string,
	description: string,
	config: AppConfig_Deserialize,
};

export type PresetInfo_Serialize = {
	id: string,
	name: string,
	description: string,
	config: AppConfig_Serialize,
};

/**  Dynamic rainbow chromatic hue cycling. */
export type RainbowConfig = {
	/**  Whether rainbow color cycling replaces static layer colors. */
	enabled: boolean,
	/**  Hue advance in degrees per 1/60 s (frame-rate independent; 2 ≈ one cycle every 3 s). */
	speed: number,
	/**  HSL saturation level (0.0 = grey, 1.0 = full vibrancy). */
	saturation: number,
	/**  HSL lightness level (0.0 = black, 0.5 = normal, 1.0 = white). */
	lightness: number,
};

/**  Click-triggered expanding shockwave ripple effects. */
export type RippleConfig = {
	/**  Whether click ripples are spawned on mouse button presses. */
	enabled: boolean,
	/**  Maximum expansion diameter in physical pixels before fading out. */
	max_diameter: number,
	/**  Lifetime duration of a ripple animation in milliseconds. */
	duration_ms: number,
	/**  Initial ring stroke width at expansion start. */
	start_width: number,
	/**  RGBA color for Left mouse button clicks. */
	color_left: [number, number, number, number],
	/**  RGBA color for Right mouse button clicks. */
	color_right: [number, number, number, number],
	/**  RGBA color for Middle (wheel) mouse button clicks. */
	color_middle: [number, number, number, number],
};

/**  Orbiting satellite bodies around the cursor. */
export type SatelliteConfig = {
	/**  Whether orbiting satellites are active. */
	enabled: boolean,
	/**  Number of satellite bodies in the orbit. */
	count: number,
	/**  Diameter of the circular orbit in physical pixels. */
	orbit_diameter: number,
	/**  Diameter of each satellite body in physical pixels. */
	size: number,
	/**  Orbit revolution speed in radians per second. */
	speed: number,
	/**  If true, spawns a second counter-rotating ring of satellites. */
	dual_ring: boolean,
	/**  Whether a faint circular orbit trajectory line is drawn. */
	show_orbit_ring: boolean,
	/**  Stroke width of the orbit trajectory ring. */
	orbit_ring_thickness: number,
	/**  RGBA color of the satellite bodies. */
	color: [number, number, number, number],
};

export type SystemDiagnostics = SystemDiagnostics_Serialize | SystemDiagnostics_Deserialize;

export type SystemDiagnostics_Deserialize = {
	os: string,
	arch: string,
	portable: boolean,
	app_version: string,
	config_path: string,
	screen_virtual_origin: [number, number],
	screen_virtual_size: [number, number],
	gpu?: GpuInfo | null,
	/**  "hook" when the OS-level mouse hook is delivering events, otherwise "poll". */
	input_backend: string,
	uptime_secs: number,
	debug_build: boolean,
	frame: FrameStats,
	/**
	 *  Result of the last global-hotkey registration, e.g. "registered 'Ctrl+Shift+E'" or an
	 *  error message when another application owns the shortcut.
	 */
	hotkey_status: string,
	/**  Display refresh rate the render loop paces to when `general.max_fps` is 0. */
	display_refresh_hz: number,
};

export type SystemDiagnostics_Serialize = {
	os: string,
	arch: string,
	portable: boolean,
	app_version: string,
	config_path: string,
	screen_virtual_origin: [number, number],
	screen_virtual_size: [number, number],
	gpu: GpuInfo | null,
	/**  "hook" when the OS-level mouse hook is delivering events, otherwise "poll". */
	input_backend: string,
	uptime_secs: number,
	debug_build: boolean,
	frame: FrameStats,
	/**
	 *  Result of the last global-hotkey registration, e.g. "registered 'Ctrl+Shift+E'" or an
	 *  error message when another application owns the shortcut.
	 */
	hotkey_status: string,
	/**  Display refresh rate the render loop paces to when `general.max_fps` is 0. */
	display_refresh_hz: number,
};

/**
 *  Physics, geometry, and layer parameters governing the cursor ribbon trail.
 * 
 *  Every field is stored in the unit it is displayed in: springs are plain fractions
 *  (`0.05` = 5% of the gap per reference frame) and frictions are plain retention factors
 *  (`0.7` = keep 70% of the velocity). Nothing is divided by 1000 or expressed in percent
 *  behind your back, so a value in the JSON is the value on the slider.
 */
export type TrailConfig = TrailConfig_Serialize | TrailConfig_Deserialize;

/**
 *  Physics, geometry, and layer parameters governing the cursor ribbon trail.
 * 
 *  Every field is stored in the unit it is displayed in: springs are plain fractions
 *  (`0.05` = 5% of the gap per reference frame) and frictions are plain retention factors
 *  (`0.7` = keep 70% of the velocity). Nothing is divided by 1000 or expressed in percent
 *  behind your back, so a value in the JSON is the value on the slider.
 */
export type TrailConfig_Deserialize = {
	/**  Master toggle for ribbon trail physics and rendering. */
	enabled: boolean,
	/**
	 *  Number of simulated discrete nodes in the spring chain (4–500). Width, fade and blur
	 *  are parameterised by node index, so this is also the length of the visible taper.
	 */
	length: number,
	/**
	 *  Spring constant for the trailing body nodes, used directly: each reference frame adds
	 *  `gap × spring` to the node's velocity (0.0–1.0). 0 = no pull, 1 = snaps shut.
	 */
	spring: number,
	/**
	 *  Fraction of velocity the body nodes keep per reference frame (0.0–1.0): 1.0 = frictionless
	 *  (rings forever), 0.0 = every node stops dead each frame.
	 */
	damping: number,
	/**  Spring constant for the leading head node, same units and range as `spring`. */
	head_spring: number,
	/**  Fraction of velocity the head keeps per reference frame, same units as `damping`. */
	head_damping: number,
	/**  LazyBrush: engage the dead-zone pointer smoother. */
	lazy_enabled?: boolean,
	/**  Dead-zone radius in px the pointer must exceed before the brush starts moving. */
	lazy_radius?: number,
	/**
	 *  Brush friction 0–0.99: fraction of the excess distance NOT applied per frame
	 *  (0 = snap to pointer, →1 = frozen). Factor: `1 - sqrt(1-(1-f)^2)`.
	 */
	lazy_friction?: number,
	/**
	 *  Reference ribbon width in physical pixels at the head; each layer scales it by its
	 *  `width_factor`.
	 */
	cursor_size: number,
	/**  Minimum clamping width in physical pixels at the tail of the trail. */
	min_width: number,
	/**  Extra width at full speed: `width × (1 + mult × min(speed / velocity_reference_speed, 1))`. */
	velocity_width_mult: number,
	/**  Extra opacity at full speed, same normalisation as `velocity_width_mult`. */
	velocity_alpha_mult: number,
	/**  Speed (px per 1/120 s reference frame) at which the velocity boosts above reach 100%. */
	velocity_reference_speed: number,
	/**
	 *  Fixed Catmull-Rom sub-samples per node segment. Only used when `adaptive_quality` is
	 *  off; the adaptive path picks its own count from the local curvature.
	 */
	interpolation_steps: number,
	/**
	 *  Falloff curve along the length of the trail
	 *  (0=Linear, 1=EaseOut, 2=Exponential, 3=Sigmoid, 4=Smoothstep).
	 */
	fade_mode: number,
	/**  Whether gradient interpolation between start and end color is applied. */
	enable_gradient: boolean,
	/**
	 *  Curvature-adaptive spline sampling (3–24 px spacing): dense in bends, sparse on straight
	 *  runs. Overrides `interpolation_steps`.
	 */
	adaptive_quality: boolean,
	/**  4-Layer Master Design: [0]=Outer Glow, [1]=Mid Shadow, [2]=Crisp Core, [3]=Inner Spine. */
	layers: [LayerConfig, LayerConfig, LayerConfig, LayerConfig],
};

/**
 *  Physics, geometry, and layer parameters governing the cursor ribbon trail.
 * 
 *  Every field is stored in the unit it is displayed in: springs are plain fractions
 *  (`0.05` = 5% of the gap per reference frame) and frictions are plain retention factors
 *  (`0.7` = keep 70% of the velocity). Nothing is divided by 1000 or expressed in percent
 *  behind your back, so a value in the JSON is the value on the slider.
 */
export type TrailConfig_Serialize = {
	/**  Master toggle for ribbon trail physics and rendering. */
	enabled: boolean,
	/**
	 *  Number of simulated discrete nodes in the spring chain (4–500). Width, fade and blur
	 *  are parameterised by node index, so this is also the length of the visible taper.
	 */
	length: number,
	/**
	 *  Spring constant for the trailing body nodes, used directly: each reference frame adds
	 *  `gap × spring` to the node's velocity (0.0–1.0). 0 = no pull, 1 = snaps shut.
	 */
	spring: number,
	/**
	 *  Fraction of velocity the body nodes keep per reference frame (0.0–1.0): 1.0 = frictionless
	 *  (rings forever), 0.0 = every node stops dead each frame.
	 */
	damping: number,
	/**  Spring constant for the leading head node, same units and range as `spring`. */
	head_spring: number,
	/**  Fraction of velocity the head keeps per reference frame, same units as `damping`. */
	head_damping: number,
	/**  LazyBrush: engage the dead-zone pointer smoother. */
	lazy_enabled: boolean,
	/**  Dead-zone radius in px the pointer must exceed before the brush starts moving. */
	lazy_radius: number,
	/**
	 *  Brush friction 0–0.99: fraction of the excess distance NOT applied per frame
	 *  (0 = snap to pointer, →1 = frozen). Factor: `1 - sqrt(1-(1-f)^2)`.
	 */
	lazy_friction: number,
	/**
	 *  Reference ribbon width in physical pixels at the head; each layer scales it by its
	 *  `width_factor`.
	 */
	cursor_size: number,
	/**  Minimum clamping width in physical pixels at the tail of the trail. */
	min_width: number,
	/**  Extra width at full speed: `width × (1 + mult × min(speed / velocity_reference_speed, 1))`. */
	velocity_width_mult: number,
	/**  Extra opacity at full speed, same normalisation as `velocity_width_mult`. */
	velocity_alpha_mult: number,
	/**  Speed (px per 1/120 s reference frame) at which the velocity boosts above reach 100%. */
	velocity_reference_speed: number,
	/**
	 *  Fixed Catmull-Rom sub-samples per node segment. Only used when `adaptive_quality` is
	 *  off; the adaptive path picks its own count from the local curvature.
	 */
	interpolation_steps: number,
	/**
	 *  Falloff curve along the length of the trail
	 *  (0=Linear, 1=EaseOut, 2=Exponential, 3=Sigmoid, 4=Smoothstep).
	 */
	fade_mode: number,
	/**  Whether gradient interpolation between start and end color is applied. */
	enable_gradient: boolean,
	/**
	 *  Curvature-adaptive spline sampling (3–24 px spacing): dense in bends, sparse on straight
	 *  runs. Overrides `interpolation_steps`.
	 */
	adaptive_quality: boolean,
	/**  4-Layer Master Design: [0]=Outer Glow, [1]=Mid Shadow, [2]=Crisp Core, [3]=Inner Spine. */
	layers: [LayerConfig, LayerConfig, LayerConfig, LayerConfig],
};

