export interface LayerConfig {
  enabled: boolean;
  start_color: [number, number, number, number];
  end_color: [number, number, number, number];
  width_factor: number;
  alpha_factor: number;
  start_blur: number;
  end_blur: number;
}

export interface AppConfig {
  enabled: boolean;
  effect_type: number;
  trail_color: [number, number, number, number];
  trail_length: number;
  trail_width: number;
  speed: number;
  friction: number;
  gravity: number;
  ripple_radius: number;
  click_response: boolean;
  head_spring: number;
  head_friction: number;
  body_spring: number;
  body_friction: number;
  position_skip: number;
  interpolation_steps: number;
  fade_mode: number;
  enable_gradient: boolean;
  rainbow_mode: boolean;
  rainbow_speed: number;
  adaptive_quality: boolean;
  min_trail_width: number;
  velocity_width_multiplier: number;
  velocity_alpha_multiplier: number;
  layers: LayerConfig[];
  head_enabled: boolean;
  head_filled: boolean;
  head_color: [number, number, number, number];
  head_size: number;
  head_outline_width: number;
  head_squish_intensity: number;
  head_squish_smoothing: number;
  ripple_left_color: [number, number, number, number];
  ripple_right_color: [number, number, number, number];
  ripple_middle_color: [number, number, number, number];
  ripple_duration: number;
  ripple_start_width: number;
  particle_enabled: boolean;
  particle_count: number;
  particle_speed: number;
  particle_lifetime: number;
  particle_size: number;
  particle_friction: number;
  particle_gravity: number;
  satellite_enabled: boolean;
  satellite_count: number;
  satellite_orbit_diameter: number;
  satellite_size: number;
  satellite_filled: boolean;
  satellite_outline_width: number;
  satellite_color: [number, number, number, number];
  satellite_speed: number;
  satellite_enable_dual_ring: boolean;
  satellite_dual_speed: number;
  satellite_show_orbit_ring: boolean;
  satellite_ring_width: number;
  satellite_ring_color: [number, number, number, number];
  start_minimized: boolean;
}
