[package]
name = "fxcursor-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "^1.0.229", features = ["derive"] }
serde_json = "^1.0.151"
serde_path_to_error = "^0.1.20"
specta = { version = "2.0.0-rc.25", features = ["derive"] }
bytemuck = { version = "^1.25.2", features = ["derive"] }
log = "^0.4.34"
